//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animale()
        {
            this.Recetas = new HashSet<Receta>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public int TipoID { get; set; }
        public int RazaID { get; set; }
        public int Edad { get; set; }
        public string Direccion { get; set; }
        public bool Inactivo { get; set; }
        public int ClienteId { get; set; }
    
        public virtual Raza Raza { get; set; }
        public virtual Tipo_Animal Tipo_Animal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receta> Recetas { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
