//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANIMAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANIMAL()
        {
            this.RECETAs = new HashSet<RECETA>();
        }
    
        public int IDANIMAL { get; set; }
        public string NOMBREANM { get; set; }
        public int IDTIPO { get; set; }
        public int IDRAZA { get; set; }
        public int EDAD { get; set; }
        public string NOMBREPRO { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual RAZA RAZA { get; set; }
        public virtual TIPO_ANIMAL TIPO_ANIMAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECETA> RECETAs { get; set; }
    }
}
