//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADO()
        {
            this.COTIZACIONs = new HashSet<COTIZACION>();
            this.FACTURAs = new HashSet<FACTURA>();
            this.USUARIOs = new HashSet<USUARIO>();
        }
    
        public int IDEMPLEADO { get; set; }
        public string NOMBREEMP { get; set; }
        public string APELLIDOEMP { get; set; }
        public int IDUSUARIO { get; set; }
        public string NOMBREUSU { get; set; }
        public string CONTRASEÑAUSU { get; set; }
        public int IDCARGO { get; set; }
        public string NOMBRECAR { get; set; }
        public int SUELDO { get; set; }
        public string DIRECCIONEMP { get; set; }
        public int IDCIUDAD { get; set; }
        public string TELEFONO { get; set; }
        public string CEDULAEMP { get; set; }
        public string CORREOEMP { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual CARGO CARGO { get; set; }
        public virtual CIUDAD CIUDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COTIZACION> COTIZACIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA> FACTURAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIOs { get; set; }
    }
}
