//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.Facturas_Detalle = new HashSet<Facturas_Detalle>();
        }
    
        public int ID { get; set; }
        public int CategoriaID { get; set; }
        public System.DateTime Fecha { get; set; }
        public int TipoFacturaID { get; set; }
        public int EmpleadoID { get; set; }
        public int ClienteID { get; set; }
        public decimal DescuentoTotal { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Total { get; set; }
        public bool Inactivo { get; set; }
    
        public virtual Categoria_Factura Categoria_Factura { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Tipo_Factura Tipo_Factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas_Detalle> Facturas_Detalle { get; set; }
    }
}
