//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA_DETALLE
    {
        public int IDDETALLE { get; set; }
        public int IDFACTURA { get; set; }
        public int IDCATEGORIA { get; set; }
        public System.DateTime FECHA { get; set; }
        public int IDTIPOFAC { get; set; }
        public int IDEMPLEADO { get; set; }
        public int IDCLIENTE { get; set; }
        public int IDPRODUCTO { get; set; }
        public string NOMBREPRO { get; set; }
        public int IDTIPOPRO { get; set; }
        public string DESCRIPCIONPRO { get; set; }
        public int PRECIOPRO { get; set; }
        public int CATIDAD { get; set; }
        public Nullable<int> DESCUENTO { get; set; }
        public Nullable<int> SUBTOTAL { get; set; }
        public Nullable<int> TOTAL { get; set; }
    
        public virtual FACTURA FACTURA { get; set; }
    }
}
