//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas_Detalle
    {
        public int ID { get; set; }
        public int FacturasID { get; set; }
        public System.DateTime Fecha { get; set; }
        public int EmpleadoID { get; set; }
        public int ProductoID { get; set; }
        public int TipoProductoId { get; set; }
        public decimal Precio { get; set; }
        public int Cantidad { get; set; }
        public decimal Descuento { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Total { get; set; }
        public bool Inactivo { get; set; }
    
        public virtual Factura Factura { get; set; }
    }
}
