//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIAL_RECETA
    {
        public int IDHIST { get; set; }
        public int IDRECETA { get; set; }
        public int IDANIMAL { get; set; }
        public string NOMBREANM { get; set; }
        public int IDDUEÑO { get; set; }
        public System.DateTime FECHA { get; set; }
        public string DIAGNOSTICO { get; set; }
        public System.TimeSpan HORA { get; set; }
        public string TRATAMIENTO { get; set; }
    
        public virtual RECETA RECETA { get; set; }
    }
}
