//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial_Recetas
    {
        public int ID { get; set; }
        public int RecetaId { get; set; }
        public int AnimalId { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Diagnostico { get; set; }
        public System.TimeSpan Hora { get; set; }
        public string Tratamiento { get; set; }
        public bool Inactivo { get; set; }
    
        public virtual Receta Receta { get; set; }
    }
}
