//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.COTIZACIONs = new HashSet<COTIZACION>();
            this.FACTURAs = new HashSet<FACTURA>();
        }
    
        public int IDPRODUCTO { get; set; }
        public string NOMBREPRO { get; set; }
        public int IDTIPOPRO { get; set; }
        public string DESCRIPCIONPRO { get; set; }
        public int IDPROVEEDOR { get; set; }
        public int COSTOPRO { get; set; }
        public int PRECIOPRO { get; set; }
        public int CANTIDADPRO { get; set; }
        public string ESTATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COTIZACION> COTIZACIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA> FACTURAs { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual TIPO_PRODUCTO TIPO_PRODUCTO { get; set; }
    }
}
