//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECETA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RECETA()
        {
            this.HISTORIAL_RECETA = new HashSet<HISTORIAL_RECETA>();
        }
    
        public int IDRECETA { get; set; }
        public int IDANIMAL { get; set; }
        public string NOMBREANM { get; set; }
        public int IDTIPO { get; set; }
        public int IDRAZA { get; set; }
        public int EDAD { get; set; }
        public string PADECIMIENTO { get; set; }
        public string PRODUCTOIND { get; set; }
        public string DOSIS { get; set; }
        public string PERSONARES { get; set; }
    
        public virtual ANIMAL ANIMAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIAL_RECETA> HISTORIAL_RECETA { get; set; }
    }
}
