//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int IDUSUARIO { get; set; }
        public int IDEMPLEADO { get; set; }
        public string NOMBREUSU { get; set; }
        public string CONTRASEÑA { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
    }
}
