//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VeterinariaEntities : DbContext
    {
        public object open;

        public VeterinariaEntities()
            : base("name=VeterinariaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animale> Animales { get; set; }
        public virtual DbSet<Cargo> Cargos { get; set; }
        public virtual DbSet<Categoria_Factura> Categoria_Factura { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Cotizacione> Cotizaciones { get; set; }
        public virtual DbSet<Empleado> Empleados { get; set; }
        public virtual DbSet<Factura> Facturas { get; set; }
        public virtual DbSet<Historial_Recetas> Historial_Recetas { get; set; }
        public virtual DbSet<Producto> Productos { get; set; }
        public virtual DbSet<Proveedor> Proveedors { get; set; }
        public virtual DbSet<Raza> Razas { get; set; }
        public virtual DbSet<Receta> Recetas { get; set; }
        public virtual DbSet<Tipo_Animal> Tipo_Animal { get; set; }
        public virtual DbSet<Tipo_Factura> Tipo_Factura { get; set; }
        public virtual DbSet<Tipo_Producto> Tipo_Producto { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Facturas_Detalle> Facturas_Detalle { get; set; }
        public virtual DbSet<Municipio> Municipios { get; set; }
        public virtual DbSet<Provincia> Provincias { get; set; }
    }
}
