//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VeterinariaEntities : DbContext
    {
        public VeterinariaEntities()
            : base("name=VeterinariaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ANIMAL> ANIMALs { get; set; }
        public virtual DbSet<CARGO> CARGOS { get; set; }
        public virtual DbSet<CATEGORIA_FACTURA> CATEGORIA_FACTURA { get; set; }
        public virtual DbSet<CIUDAD> CIUDADs { get; set; }
        public virtual DbSet<CLIENTE> CLIENTEs { get; set; }
        public virtual DbSet<COTIZACION> COTIZACIONs { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADOes { get; set; }
        public virtual DbSet<FACTURA> FACTURAs { get; set; }
        public virtual DbSet<FACTURA_DETALLE> FACTURA_DETALLE { get; set; }
        public virtual DbSet<HISTORIAL_RECETA> HISTORIAL_RECETA { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTOes { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDORs { get; set; }
        public virtual DbSet<RAZA> RAZAs { get; set; }
        public virtual DbSet<RECETA> RECETAs { get; set; }
        public virtual DbSet<TIPO_ANIMAL> TIPO_ANIMAL { get; set; }
        public virtual DbSet<TIPO_FACTURA> TIPO_FACTURA { get; set; }
        public virtual DbSet<TIPO_PRODUCTO> TIPO_PRODUCTO { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
    }
}
